### PR TITLE
Fix #127, add "pushbutton" sound (questionable), make raccoon guy better

### LINKED ISSUE #127: [Bug] Game crashes when placing/drawing specific animated tiles
image
It only seems to happen with specific animated tiles. Upon examination of the .txt files, there is nothing wrong with them, nor is there anything wrong with the images themselves, I double-checked to see if the dimensions are correct, and they are.

You can see and select this tile from the menu without the game crashing, but when you place it in the level, or one gets drawn in a level that had them previously, the game crashes.

The only modifications to the game are the font, fontback, smallfont, 1uptext and replaced sound effects, which shouldn't be interfering with the animated tiles anyway.

### PR DESCRIPTION
**Pull request by Frostplays-ZERO**
Thanks for making me a member, Hugo. What privileges does it give me? Not editing rights, apparently. (Not complaining.)

### CODE REVIEW

**Comment by HugoBDesigner** [comment]
Sorry for the delay in responding. Would it be possible for you to remove the 2x2 tile property for the time being? I had a different idea for implementing those without taking over a tile property slot.
I wanted to implement tile grouping like I did in HEC.  It's somewhat similar to the existing "objects" feature, except it ties the group to the top-right tile:
editorgroupsupdate_gif

**Comment by Frostplays-ZERO** [comment]
It's in Release 1.4, so removing it might be a bit odd, but it'd take me about 5 minutes if you really want me to.

**Comment by HugoBDesigner** [comment]
Alright, now that I finally had time to work out these features, it's time to merge. I've tested them as much as I could, but do make sure to test it further so we might find lurking bugs and errors 👍

**Comment by Frostplays-ZERO** [comment]
It's a bit odd that you pushed commits to my fork, but ok. I don't think the "unbind" key is working, FYI.

**Comment by HugoBDesigner** [comment]
I figured that, since I was going to merge your fork, I'd use the opportunity and push everything together :P 
The "unbind group" key has to be used in the tiles screen, like so:

And what exactly is odd about renaming objects? From my testing, it seems to behave fine.

**Pull request merged**
